[IBMRACK]
base_url = https://srvibmpod.ibm.com
username = rsaQ
password = KF**f*)D;KF1F

[PATHS]
save_folder = output
driver_path = msedgedriver.exe

[RACKS]
rack_prefixes = 1FX,47B

[RACK_LOC]
location = 1FX02,1FX11,47B13

[ALERT_CONDITION]
#network_status can Offine | Online
network_status = Offline
#power_status can be Offine | Online
power_status = Offline
#test_status = FAIL | PASS | RUNNING | WARNING
test_status = FAIL
#idle_time in minutes
idle_time = 5200
